from DisplacedSUSY.Configuration.histogramDefinitions import ElectronHistograms, DiElectronHistograms, ElectronJetHistograms, ElectronMetHistograms
from DisplacedSUSY.Configuration.histogramDefinitions import ElectronD0Histograms
from DisplacedSUSY.StandardAnalysis.BasicHistograms import *

histograms.append(ElectronHistograms)
histograms.append(DiElectronHistograms)
histograms.append(ElectronD0Histograms)
histograms.append(ElectronJetHistograms)
histograms.append(ElectronMetHistograms)
