from DisplacedSUSY.Configuration.histogramDefinitions import ElectronHistograms, DiElectronHistograms, ElectronJetHistograms, ElectronMetHistograms, PhotonHistograms
from DisplacedSUSY.Configuration.histogramDefinitions import ElectronD0Histograms, ElectronPhotonHistograms
from DisplacedSUSY.StandardAnalysis.BasicHistograms import *

histograms.append(ElectronHistograms)
histograms.append(DiElectronHistograms)
histograms.append(ElectronD0Histograms)
histograms.append(ElectronJetHistograms)
histograms.append(ElectronMetHistograms)
histograms.append(PhotonHistograms)
histograms.append(ElectronPhotonHistograms)
